version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    environment:
      MYSQL_ROOT_PASSWORD: MySQLPassword
      MYSQL_DATABASE: sistem_za_regrutaciju
    ports:
      - "3306:3306"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - mynetwork  # Define the network that flask will connect to

  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql  # Connect to the 'mysql' service defined in docker-compose
      MYSQL_USER: root
      MYSQL_PASSWORD: MySQLPassword
      MYSQL_DATABASE: sistem_za_regrutaciju
    ports:
      - "8080:8080"
    networks:
      - mynetwork  # Connect to the same network as the mysql service

# Define the network 'mynetwork' for connecting services
networks:
  mynetwork:
    driver: bridge  # Standard Docker network