version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    environment:
      MYSQL_ROOT_PASSWORD: MySQLPassword
      MYSQL_DATABASE: sistem_za_regrutaciju
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"
    networks:
      - mynetwork  # Ovdje koristimo mrežu 'mynetwork'

  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - mynetwork  # I ovde se povezuje na istu mrežu 'mynetwork'

# Definišemo mrežu 'mynetwork'
networks:
  mynetwork:
    driver: bridge  # Ovo je standardna mreža za povezivanje servisa unutar Docker-a