# Use official MySQL image
FROM mysql:8.0

# Set environment variables (ako su potrebne)
ENV MYSQL_ROOT_PASSWORD=MySQLPassword
ENV MYSQL_DATABASE=sistem_za_regrutaciju

# Copy dump.sql for database initialization
COPY dump.sql /docker-entrypoint-initdb.d/

# Expose MySQL port
EXPOSE 3306