version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    environment:
      MYSQL_ROOT_PASSWORD: MySQLPassword
      MYSQL_DATABASE: sistem_za_regrutaciju
    ports:
      - "3306:3306"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - mynetwork

  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql  # The MySQL service defined in docker-compose
      MYSQL_USER: root
      MYSQL_PASSWORD: MySQLPassword
      MYSQL_DATABASE: sistem_za_regrutaciju
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge