# Start from a Python image
FROM python:3.13-slim

# Set the working directory
WORKDIR /app

# Install the dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose port 8080 to communicate with the outside world
EXPOSE 8080

# Start the application using gunicorn
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:8080"]