version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MySQLPassword
      MYSQL_DATABASE: sistem_za_regrutaciju
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "8080:8080"
    depends_on:
      - mysql