# Koristi Python 3.13 kao osnovnu sliku
FROM python:3.13-slim

# Postavi radnu direktoriju
WORKDIR /app

# Kopiraj requirements.txt i instaliraj zavisnosti
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Kopiraj ostatak aplikacije
COPY . .

# Eksponiraj port
EXPOSE 8080

# Pokreni Flask aplikaciju
CMD ["python", "app.py"]